source 'https://rubygems.org'

gem 'rails', '4.2.5'
gem 'pg', '~> 0.15'

gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'haml-rails'
gem 'devise'
gem 'will_paginate'

gem 'rails_12factor', group: :production
group :development, :test do
  gem 'byebug'
  gem 'rspec-rails'
  gem 'faker'
  gem 'pry-rails'
  gem 'capybara'
  gem 'selenium-webdriver'
  gem 'database_cleaner'
end

